### ISSUE TITLE
Moon is broken sometimes

### ISSUE THREAD

**Issue by g4s8** [valignatev/python-snowterm#2]
Time to time moon lines are jumping to left, see screenshot:
![scrot-2018-12-29-16 50 00](https://user-images.githubusercontent.com/1524988/50538979-e1e7ca00-0b89-11e9-996c-107209f2deb2.png)

**Comment by valignatev** [comment]
Thanks for the issue. Just for the record, what OS/terminal emulator it is?

**Comment by g4s8** [comment]
@valignatev OS: `Gentoo/Linux`, tried on two termials [alacritty](https://github.com/jwilm/alacritty) and [urxvt](http://rxvt.sourceforge.net/) - same moon issues.

**Comment by valignatev** [comment]
I've failed to reproduce on both alacritty and urxvt unfortunately, but I've simplified moon drawing function, now it doesn't check symbols, but draws them right away. Maybe now it will be ok for you.

**Comment by g4s8** [comment]
@valignatev thanks, now it's rendering correctly.
