### ISSUE TITLE
Variables outside loops

### ISSUE THREAD

**Issue by scebotari66** [valignatev/python-snowterm#3]
Just a curiosity of mine. I have no python experience whatsoever. Coming from a javascript background and having dealt with performance problems related to loops. Isn't it a good idea to move the `max_width` and `max_height` outside of `for` loops?

**Comment by valignatev** [comment]
This is a good question actually. First, I admit that in order to make the code as simple as possible, I've sacrificed performance here and there. Second, obtaining max height and width in the loop makes terminal resizing in the real-time possible.

**Comment by scebotari66** [comment]
Yes, resizing is important. Thanks for the explanation!
